server:
  port: 8001

spring:
  application:
    name: cloud-payment-service-eureka
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: org.gjt.mm.mysql.Driver
      url: jdbc:mysql://127.0.0.1:3306/spring-cloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: root
eureka:
  client:
    register-with-eureka: true   #是否将自己注册到注册中心(Eureka-Server)
    fetch-registry: false    #是否从服务端抓取已有的注册信息,默认为true,集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
      #defaultZone: http://eureka7001.com:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #集群
  instance:
    instance-id:  payment8001 #服务实例名称
    prefer-ip-address: true  #是否显示ip地址
    lease-renewal-interval-in-seconds: 30  #向Eureka-Server 发送心跳的时间间隔
    lease-expiration-duration-in-seconds: 90 #Eureka-Server收到最后一次心跳后等待的时间上限

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hww.entities
