server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
         locator:
           enabled: true  #开启从注册中心动态创建路由的功能，利用微服务名称进行路由
      routes:
        - id: payment_routh                 #路由的id,没有规则，必须唯一
          #uri: http://localhost:8001        #匹配后，提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE-EUREKA
          predicates:
            - Path=/payment/get/**          #断言：路径匹配的进行路由
            - Cookie=username,hww
            - Header=X-Request-Id, \d+ #请求头要有X-Request-Id的字段且值为整数的正则表达式
        - id: payment_routh2
          #uri: http://localhost:8001
          uri: lb://CLOUD-PAYMENT-SERVICE-EUREKA
          predicates:
            - Path=/payment/create/**       #断言：路径匹配的进行路由
eureka:
  client:
    register-with-eureka: true   #是否将自己注册到注册中心(Eureka-Server)
    fetch-registry: true    #是否从服务端抓取已有的注册信息,默认为true,集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id:  cloud-gateway-service #服务实例名称
    prefer-ip-address: true  #是否显示ip地址
    lease-renewal-interval-in-seconds: 30  #向Eureka-Server 发送心跳的时间间隔
    lease-expiration-duration-in-seconds: 90 #Eureka-Server收到最后一次心跳后等待的时间上限



