server:
  port: 8001

spring:
  application:
    name: cloud-provider-service-hystrix
eureka:
  client:
    register-with-eureka: true   #是否将自己注册到注册中心,集群必须设置为true配合ribbon
    fetch-registry: true    #是否从服务端抓取已有的注册信息
    service-url:
       defaultZone: http://eureka7001.com:7001/eureka
      #defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #集群
  instance:
    instance-id:  order80 #服务实例名称
    prefer-ip-address: true


