server:
  port: 8801

spring:
  application:
    name: cloud-stream-kafka-provider
  cloud:
      stream:
        kafka:
          binder:
            brokers: 192.168.253.134:9092
            auto-create-topics: true
            auto-add-partitions: true
            min-partition-count: 1           #最小分区数
        bindings:                            #服务的整合处理
          output:                            #这个名字是一个通道的名称
            destination: stream-kafka-demo   #表示要使用的队列名称名称
            content-type: application/json   #设置消息类型，本次为json，文本则设置“text/plain”，，接收端不用指定格式，但是发送端要
eureka:
  client: # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    lease-renewal-interval-in-seconds: 30 # 设置心跳的时间间隔（默认是30秒）
    lease-expiration-duration-in-seconds: 90 # 如果现在超过了5秒的间隔（默认是90秒）
    instance-id: send-8801.com  # 在信息列表时显示主机名称
    prefer-ip-address: true     # 访问的路径变为IP地址







